### PR TITLE
[rebased] Base YadisServiceManager, OpenIDServiceEndpoint on dict to make them serializable

### PR DESCRIPTION
**Pull request by necaris**
Updated & rebased version of #68 , with thanks to @ofalk 

> Both objects end up as data in a serialized object, when used with django-openid-auth. Django switched to JSONSerializer that can no longer serialize these objects (in contrast to the Picke-based serializer) and hence throws an error. The easiest solution is to base both on dict objects that can be easily be serialized by JSON, but it also requires us to create corresponding getter/setter methods, plus ensure if we end up with a plain dict, we "convert" that to the real object: The new _from_dict() functions.

> This problem has been described in the past, but the usual workaround was to switch to PickleSerializer, which poses a security risk and isn't actually a real fix. Pre-Django 5.x using the Pickle-based serializer worked, but now it's completely gone and that workaround is no longer an option.

> This is my take on fixing the underlying issue of YaidServiceManager and OpenIDServiceEndpoint not being serializable with JSON session serializer.

> Refs:
> https://github.com/openid/python-openid/issues/17
> https://stackoverflow.com/questions/20301338/django-openid-auth-typeerror-openid-yadis-manager-yadisservicemanager-object-is

### CODE REVIEW

**Comment by ofalk** [comment]
Thanks a ton!

**Comment by ofalk** [comment]
If you need someone to test this in a semi-production environment (libravatar staging env), please let me know!

**Comment by necaris** [comment]
@ofalk if you're able to test this in a live environment I'd very much appreciate it -- I don't have anything resembling a live environment and I don't have much confidence in the tests.

**Comment by ofalk** [comment]
> @ofalk if you're able to test this in a live environment I'd very much appreciate it -- I don't have anything resembling a live environment and I don't have much confidence in the tests.

Alright, the following to reproduce (within the venv):
```
git clone https://github.com/necaris/python3-openid.git
cd python3-openid/
curl https://patch-diff.githubusercontent.com/raw/necaris/python3-openid/pull/71.diff|patch -p1
python setup.py install
```

In my (aging) Python 3.6 / Django 3.2.25 env (other deps all up2date), I get the following:

```
'Discovery' object has no attribute '_from_dict'
```
(downgrading to the current stable python3-openid, however doesn't solve the problem...)

So maybe it's just time to get that environment upgraded.

In my Python 3.11.5 / Django 5.1.2 env (all other deps up2date) , everything works smoothly.

I hope that helps.

**Comment by necaris** [comment]
> 
> In my (aging) Python 3.6 / Django 3.2.25 env (other deps all up2date), I get the following:
> 
> ```
> 'Discovery' object has no attribute '_from_dict'
> ```
> 

Thank you! This turned out to be a bug -- we were calling `manager = Discovery._from_dict()` instead of `manager = YadisServiceManager._from_dict()`.

Could you verify the latest update of this branch in your aging environment?

**Comment by ofalk** [comment]
> > In my (aging) Python 3.6 / Django 3.2.25 env (other deps all up2date), I get the following:
> > ```
> > 'Discovery' object has no attribute '_from_dict'
> > ```
> 
> Thank you! This turned out to be a bug -- we were calling `manager = Discovery._from_dict()` instead of `manager = YadisServiceManager._from_dict()`.
> 
> Could you verify the latest update of this branch in your aging environment?

Does work well in the new env (py 3.11, Django 5.1.2), throws an error in the old env (py 3.6.8) Django 3.2.25:

```
TypeError at /openid/login/

__init__() got an unexpected keyword argument '_current'
```

But I'm not 100% convinced if this should still support that old env.

**Comment by necaris** [comment]
> Does work well in the new env (py 3.11, Django 5.1.2), throws an error in the old env (py 3.6.8) Django 3.2.25:
> 
> ```
> TypeError at /openid/login/
> 
> __init__() got an unexpected keyword argument '_current'
> ```
> 
> But I'm not 100% convinced if this should still support that old env.

If you don't mind, let's give it one more try with https://github.com/necaris/python3-openid/commit/bd2c1484e38f8c97636a8553c0192dd096814b5e ?

**Comment by ofalk** [comment]
> > But I'm not 100% convinced if this should still support that old env.
> 
> If you don't mind, let's give it one more try with [bd2c148](https://github.com/necaris/python3-openid/commit/bd2c1484e38f8c97636a8553c0192dd096814b5e) ?

```
# git reset --hard
# curl https://github.com/necaris/python3-openid/commit/bd2c1484e38f8c97636a8553c0192dd096814b5e.patch | patch -p1
# python setup.py install
```

No change (old env):
```
TypeError at /openid/login/

__init__() got an unexpected keyword argument '_current'
```

**Comment by necaris** [comment]
Thank you @ofalk for the second try! On that basis I'll go ahead and merge, since as you say you're not sure if it should work, and it doesn't seem worthwhile to spend more effort trying to get it working.

**Comment by ofalk** [comment]
> Thank you @ofalk for the second try! On that basis I'll go ahead and merge, since as you say you're not sure if it should work, and it doesn't seem worthwhile to spend more effort trying to get it working.

Agree, looking into this issue with Django 3.2.x that is no longer supported doesn't make sense. It's really time for me to update that instance ;-)

**Comment by ofalk** [comment]
> > Thank you @ofalk for the second try! On that basis I'll go ahead and merge, since as you say you're not sure if it should work, and it doesn't seem worthwhile to spend more effort trying to get it working.
> 
> Agree, looking into this issue with Django 3.2.x that is no longer supported doesn't make sense. It's really time for me to update that instance ;-)

Minimal upgrade to Django 4.2.16, Python 3.8:
```
.virtualenv/lib/python3.8/site-packages/openid/yadis/manager.py, line 158, in getManager
Exception Value:  'dict' object has no attribute 'forURL'
```

So even Django 4.2 seems to be too old. No worry please, just for the sake of documenting it.
